[project]
name = "automotive-parts-vision"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11,<3.12"
dependencies = [
    "matplotlib>=3.11.1",
    "opencv-python>=5.0.0.93",
    "paddleocr>=3.7.0",
    "pillow>=12.3.0",
]

[project.scripts]
automotive-parts-vision = "automotive_parts_vision:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"
